services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: captain
      POSTGRES_PASSWORD: squawkvfr
      POSTGRES_DB: rocketjunior
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./be/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:7.4.0-alpine
    restart: always
    ports:
      - 6379:6379
  api: &api_base
    build:
      context: ./be
      dockerfile: ./Dockerfile
    restart: always
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./be/.env
    environment:
      PYTHONPATH: /app
    entrypoint: /app/entrypoint.sh
    ports:
      - 8000:8000
    volumes:
      - ./be:/app
    depends_on:
      - db
      - redis
  migrations:
    <<: *api_base
    restart: 'no'
    command: python manage.py migrate
    ports: []
  fe:
    build:
      context: ./fe
      dockerfile: ./Dockerfile
    restart: always
    working_dir: /app
    command: npm start
    ports:
      - 3000:3000
    depends_on:
      - db
      - api
volumes:
  pgdata: