# Generated by Django 5.1.5 on 2025-01-25 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0005_alter_attribute_entity_alter_entity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='data_type',
            field=models.CharField(
                choices=[('str', 'String'), ('int', 'Integer'), ('flt', 'Float')],
                default='str',
                max_length=3
            ),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='entity',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='descendants',
                to='entity.entity'
            ),
        ),
    ]
