# Generated by Django 5.1.5 on 2025-01-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0006_alter_attribute_data_type_alter_entity_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='tree_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
