# Generated by Django 5.1.5 on 2025-01-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0007_entity_tree_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('parent__isnull', False),
                    ('path__isnull', False)
                ),
                fields=('parent', 'path'),
                name='unique_parent_path'
            ),
        ),
    ]
