# Generated by Django 5.1.5 on 2025-01-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0008_entity_unique_parent_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='data_type',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
