# Generated by Django 5.1.5 on 2025-01-26 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0009_remove_attribute_data_type_alter_attribute_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['path']},
        ),
    ]
