# Generated by Django 5.1.5 on 2025-01-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0010_alter_attribute_options_alter_entity_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='entity',
            name='path',
            field=models.CharField(blank=True, db_index=True, max_length=2048, null=True),
        ),
    ]
