# Generated by Django 5.1.5 on 2025-01-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0012_alter_attribute_value'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attribute',
            constraint=models.UniqueConstraint(condition=models.Q(('entity__isnull', False), ('key__isnull', False)), fields=('entity', 'key'), name='unique_entity_key'),
        ),
    ]
