# Generated by Django 5.1.5 on 2025-01-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0015_alter_attribute_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='str_value',
            field=models.CharField(default=0, max_length=31),
            preserve_default=False,
        ),
    ]
