# Generated by Django 5.1.5 on 2025-01-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_alter_entity_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='data_type',
            field=models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('dec', 'Decimal')], default='str', max_length=3),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='path',
            field=models.CharField(default='/', max_length=2048),
            preserve_default=False,
        ),
    ]
