# Generated by Django 5.1.5 on 2025-01-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_alter_attribute_data_type_alter_entity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='path',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
