# Generated by Django 5.1.5 on 2025-01-24 04:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_alter_entity_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='entity.entity'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=256, unique=True, validators=[django.core.validators.RegexValidator('[/]', inverse_match=True)]),
        ),
    ]
